### ISSUE TITLE
Why is this needed?

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-availability_globalrole#1]
There is another plugin of yours availability_coursecatrole. I can't understand why there needs to be two of them. Is not a "global role" just a special case of "course category role" - when the course category being the root category?

Why there needs to be two plugins to have installed (and to maintain) rather than focusing on a sing;le plugin that would cover both use cases in a robust way?

**Comment by rschrenk** [comment]
Hi David,

yes and no. You are right, that both plugins do more or less the same. But on the other hand, Moodle separates roles by the context type where they can be assigned. You can have roles, that are ONLY assigned globally, and you can have roles that are ONLY assigned in a course category. Surely, you can also have roles, that are possible in both context types.

It seemed more transparent to me to make separate availability plugins for these different purposes.

As an availability plugin is not very complex I think that the maintenance will not be very problematic.

Kind regards

**Comment by mudrd8mz** [comment]
Right. But it's not only about _your_ maintenance costs. It's more about the extra work for all the admins who would consider to have this.

Additionally - as the `availability_coursecatrole` uses the `get_user_roles()` which checks all the contexts in the hierarchy up to the root one, it actually already works for the global roles, too. I still don't see why we should offer these two as separate plugins.

And even more - the `get_user_roles()` would also work for the roles assigned at the context of the course itself right? So that plugin's name is actually confusing and it could easily be just "Role condition" (unless I am missing something).

**Comment by mudrd8mz** [comment]
> would also work for the roles assigned at the context of the course itself right

If you allowed such a role to be selectable, I forgot to add.

**Comment by rschrenk** [comment]
Yes, a unified availability plugin for all kind of roles would make sense. But the default availability plugin does only allow course roles. Perhaps this one can be extended?

**Comment by mudrd8mz** [comment]
> the default availability plugin

May I ask for clarification - what do you mean by the default availability plugin here?

**Comment by rschrenk** [comment]
Oh, I thought it is part of Moodle Core, but it isn‘t —> https://moodle.org/plugins/availability_role

**Comment by mudrd8mz** [comment]
Right. So, my point was to suggest that we focus just on the availability_coursecatrole only as it seems to cover the case of global roles, too. Ideally, all these three (your two and Ulm's existing one) should IMHO be covered by a single unified plugin. But I don't know if there is chance for such an agreement.

**Comment by mudrd8mz** [comment]
For the record, I'll be waiting for you to share your point of view on this here. I don't think any of the raised points is a blocker here and if you insist on having both `availability_globalrole` and `availability_coursecatrole` submitted as new plugins, we will proceed (even though I would discourage from doing so as I tried to explain above).

**Comment by rschrenk** [comment]
Dear David, I will have a look at this. We are currently preparing several plugins for an upgrade to Moodle 3.8/3.9 until this summer. Once I have resources again for these plugins, I will take your arguments into consideration. Greetz from Vienna!

**Comment by mudrd8mz** [comment]
OK, great. Many thanks for the info. I will then focus on `availability_coursecatrole` at the moment and will mark `availability_globalrole` as needing more work until we hear back from you.

Good luck with your projects!

**Comment by abias** [comment]
Hey all,

I became aware of this discussion through @mudrd8mz 's ping on https://tracker.moodle.org/browse/CONTRIB-8022.

I just offered a collaboration in https://tracker.moodle.org/browse/CONTRIB-8022?focusedCommentId=802125&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-802125 and would be happy to discuss the details with you if you are interested, too.

Cheers,
Alex

**Comment by rschrenk** [comment]
This code is now part of availability_role (current fork https://github.com/center-for-learning-management/moodle-availability_role).
